List<String> letterArgs = [
  "-f",
  "-c",
  "-i",
  "-z",
  "-x",
  "-l",
  "-r",
  "-t",
  "-b",
  "-s",
  "-p",
  "-u",
  "-d",
  "-v",
  "-w",
  "-h",
  "-V",
];

List<String> extendedArgs = [
  "file",
  "class",
  "instance",
  "layer",
  "exclusive-layer",
  "left-margin",
  "right-margin",
  "top-margin",
  "bottom-margin",
  "left-anchor",
  "right-anchor",
  "top-anchor",
  "bottom-anchor",
  "toggle-visibility",
  "width",
  "height",
  "version",
];

List<String> argsDescriptions = [
  "Specifies the name of the YAML Configuration file to use (without `.yaml` extension). No other Arguments can be supplied together with this one",
  "Name of the Class of the `Shader` or `Paintable` to modify the Window Properties of. Properties apply to all Windows if no Class Name is specified",
  "Name of the Instance with which to run `WayVes`. Defaults to `default` if no value is specified.",
  "Changes the layer of the Window. 0: `Background`, 1: `Bottom`, 2: `Top`, 3: `Overlay`",
  "Specifies whether to enable Exclusive Layer for this Window. 0: `False`, 1: `True`",
  "Specifies the Left Margin of the Window",
  "Specifies the Right Margin of the Window",
  "Specifies the Top Margin of the Window",
  "Specifies the Bottom Margin of the Window",
  "Specifies whether the Window should be anchored to the Left Edge. 0: `False`, 1: `True`",
  "Specifies whether the Window should be anchored to the Right Edge. 0: `False`, 1: `True`",
  "Specifies whether the Window should be anchored to the Top Edge. 0: `False`, 1: `True`",
  "Specifies whether the Window should be anchored to the Bottom Edge. 0: `False`, 1: `True`",
  "Toggles the Visibility of the Window. Specifying 0 or 1 with the argument will enforce the Visibility to be On or Off.  Note that the `Paintable` Objects also get the same visibility as that of the primary `Shader` they mirror.",
  "Specifies Window Width",
  "Specifies Window Height",
  "Prints the current Version",
];
